wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.13
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1649347858
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      4: 3.9.10
      5: 0.12.13
      8:
      - 5
